version: '3.8'

services:
  app:
    image: bbahaida/driveanddeliver:latest
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      - POSTGRESQL_DATABASE=mydatabase
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypassword
    volumes:
      - postgres_data:/bitnami/postgresql
    ports:
      - '5432:5432'
    networks:
      - app-network


volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
