name: BB Pipeline
on: push
jobs:
  bb-jib:
    name: Auto jib
    runs-on: ubuntu-latest
    environment: dd-env
    steps:
      - uses: actions/checkout@v2
      - name: Set executable permissions for gradlew
        run: chmod +x gradlew
        working-directory: ${{ github.workspace }} 
      - uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build jib
